# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff290139d687ef6920f9636ae608ffca6e9fdaece17ae7ef688dfe3728733ce98a94404f87b12d4bc012e8602216d0b79f60d99b8d029bcaa95eecb91b2fc20f

test:
  secret_key_base: d558dcb802fc1e81f82fd47e0c1a9cd3241e0409dcc1607f147ba6375a39fa228f995700eb93ccdec5b06e187e7474156bc0779da2202431090ba3edad7fb7b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
